name: Trase Bot Analyzer (Daily 10:10 KSA)

on:
  schedule:
    - cron: "10 7 * * *"   # 07:10 UTC = 10:10 Asia/Riyadh
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Configure ENV
        env:
          FUNNEL_EXPORT_URL: ${{ secrets.FUNNEL_EXPORT_URL }}
          FUNNEL_WEBHOOK_URL: ${{ secrets.FUNNEL_WEBHOOK_URL }}
          FUNNEL_WEBHOOK_TOKEN: ${{ secrets.FUNNEL_WEBHOOK_TOKEN }}
          EMAIL_ENABLED: "false"
          WEEK_OVER_WEEK_THRESHOLD_PCT: "15"
          RATE_VARIANCE_BAND_PCT: "15"
          NOT_SPENDING_THRESHOLD_PCT: "20"
        run: |
          echo "ENV ready"

      - name: Run analyzer
        env:
          FUNNEL_EXPORT_URL: ${{ secrets.FUNNEL_EXPORT_URL }}
          FUNNEL_WEBHOOK_URL: ${{ secrets.FUNNEL_WEBHOOK_URL }}
          FUNNEL_WEBHOOK_TOKEN: ${{ secrets.FUNNEL_WEBHOOK_TOKEN }}
        run: |
          python trase_analyzer.py

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: out/*.csv
