name: Trase Bot Analyzer (Daily 10:10 KSA)

on:
  schedule:
    - cron: "10 7 * * *"   # 07:10 UTC = 10:10 Riyadh
  workflow_dispatch:

concurrency:
  group: trase-analyzer
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Preflight – validate env & files
        env:
          FUNNEL_EXPORT_URL: ${{ secrets.FUNNEL_EXPORT_URL }}
          FUNNEL_WEBHOOK_URL: ${{ secrets.FUNNEL_WEBHOOK_URL }}
          FUNNEL_WEBHOOK_TOKEN: ${{ secrets.FUNNEL_WEBHOOK_TOKEN }}
        run: |
          set -e
          echo "Checking required ENV…"
          [ -z "$FUNNEL_EXPORT_URL" ] && echo "❌ FUNNEL_EXPORT_URL is missing" && exit 1 || echo "✅ FUNNEL_EXPORT_URL present"
          [ -z "$FUNNEL_WEBHOOK_URL" ] && echo "❌ FUNNEL_WEBHOOK_URL is missing" && exit 1 || echo "✅ FUNNEL_WEBHOOK_URL present"
          echo "Checking repo files…"
          [ -f config/media_plan.csv ] && echo "✅ config/media_plan.csv found" || (echo "⚠️ media_plan.csv missing – creating sample"; mkdir -p config; printf "client,brand,market,platform,campaign,objective,total_budget,duration_days,daily_cap,target_CPC,target_CPL,target_CPM,target_CPV\nClient A,Brand X,KSA,Meta,Campaign 1,Conversions,10000,30,400,2.00,10.00,8.00,0.05\nClient B,Brand Y,KSA,Meta,Campaign 2,Awareness,8000,30,300,2.50,12.00,9.00,0.06\n" > config/media_plan.csv)

      - name: Run analyzer
        env:
          FUNNEL_EXPORT_URL: ${{ secrets.FUNNEL_EXPORT_URL }}
          FUNNEL_WEBHOOK_URL: ${{ secrets.FUNNEL_WEBHOOK_URL }}
          FUNNEL_WEBHOOK_TOKEN: ${{ secrets.FUNNEL_WEBHOOK_TOKEN }}
          EMAIL_ENABLED: "false"
          WEEK_OVER_WEEK_THRESHOLD_PCT: "15"
          RATE_VARIANCE_BAND_PCT: "15"
          NOT_SPENDING_THRESHOLD_PCT: "20"
          # Optional override for path
          MEDIA_PLAN_PATH: "config/media_plan.csv"
        run: |
          set -euxo pipefail
          python -V
          python trase_analyzer.py | tee run.log

      - name: Upload outputs & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trase-outputs
          path: |
            out/*.csv
            run.log
          if-no-files-found: warn
